### PR TITLE
feat: upgrade to casbin v2

### LINKED ISSUE #9: Support for Latest Casbin.NET Version
Are there plans to update to the latest version of Casbin.NET soon to account for the updates to the watcher interfaces? The current release is not compatible with v2.1.1 of Casbin.NET. Thanks

### PR DESCRIPTION
**Pull request by msfreed**
Fix: https://github.com/casbin-net/redis-watcher/issues/9

* Dropped support for netcoreapp3.1 and net5.0
* Dropped Newtonsoft in favor of System.Text.Json
* Added support for net8.0
* Upgraded package references
* Simplified RedisWatcher and removed the generic version

### CODE REVIEW

**Comment by hsluoyz** [comment]
@msfreed plz fix CI:

image

**Comment by msfreed** [comment]
How do you guys feel about only supporting MS supported target frameworks (e.g. net6, net7, net8, netstandard2.1)?

**Comment by hsluoyz** [comment]
> How do you guys feel about only supporting MS supported target frameworks (e.g. net6, net7, net8, netstandard2.1)?

@msfreed is it easy to keep net5 support? If it's not, it's also OK to upgrade

**Comment by hsluoyz** [comment]
@msfreed plz sign CLA

image

**Comment by msfreed** [comment]
I've signed a few times, not sure why it isn't recognized yet

**Pull request merged**
